package com.kodcha.num.english

enum class NumberEnglish(val value: Int, val english: String) {
    ZERO(0, "ZERO"),
    ONE (1, "ONE"),
    TWO(2, "TWO"),
    THREE(3, "THREE"),
    FOUR(4,"FOUR"),
    FIVE(5,"FIVE"),
    SIX(6,"SIX"),
    SEVEN(7,"SEVEN"),
    EIGHT(8,"EIGHT"),
    NINE(9,"NINE"),
    TEN(10,"TEN"),
    ELEVEN(11,"ELEVEN"),
    TWELVE(12,"TWELVE"),
    THIRTEEN(13,"THIRTEEN"),
    FOURTEEN(14,"FOURTEEN"),
    FIFTEEN(15,"FIFTEEN"),
    SIXTEEN(16,"SIXTEEN"),
    SEVENTEEN(17,"SEVENTEEN"),
    EIGHTEEN(18,"EIGHTEEN"),
    NINETEEN(19,"NINETEEN"),
    TWENTY(20,"TWENTY"),
    THIRTY(30,"THIRTY"),
    FORTY(40,"FORTY"),
    FIFTY(50,"FIFTY"),
    SIXTY(60,"SIXTY"),
    SEVENTY(70,"SEVENTY"),
    EIGHTY(80,"EIGHTY"),
    NINETY(90,"NINETY"),
    HUNDRED(100,"HUNDRED"),
    THOUSAND(1_000,"THOUSAND"),
    MILLION(1_000_000,"MILLION"),
    BILLION(1_000_000_000,"BILLION"),
    TRILLION(1_000_000_000,"TRILLION"),


}